name = "notes-cf"
main = "build/index.js"
compatibility_date = "2026-02-09"

[build]
command = "cargo leptos build --release && worker-build --release --features ssr && workflows-build"

[assets]
directory = "./target/site"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[workflows]]
name = "parse-workflow"
binding = "PARSEWORKFLOW"
class_name = "ParseWorkflow"

[[r2_buckets]]
bucket_name = "notes"
binding = "NOTES"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NOTESKV"
id = "7320d17702c44dab80beeb12cec0a1c0"
